# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bird <- function(infile0, outfile0, outfile_expr0, libfile0 = "./src/human_hg19_model.bin", locus_model = 0L, up_bound = 14, match_mode = 0L, write_flag = 0L) {
    .Call('_scBIRD_bird', PACKAGE = 'scBIRD', infile0, outfile0, outfile_expr0, libfile0, locus_model, up_bound, match_mode, write_flag)
}

getLoci <- function(libfile0) {
    .Call('_scBIRD_getLoci', PACKAGE = 'scBIRD', libfile0)
}

bird_select_loci <- function(infile0, loci_size_tmp, select_loci_tmp, libfile0 = "./src/human_hg19_model.bin", locus_model = 0L, up_bound = 14, match_mode = 0L, write_flag = 0L) {
    .Call('_scBIRD_bird_select_loci', PACKAGE = 'scBIRD', infile0, loci_size_tmp, select_loci_tmp, libfile0, locus_model, up_bound, match_mode, write_flag)
}

