# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict <- function(infile0, outfile0, outfile_expr0, locus_model = 0L, up_bound = 14, match_mode = 0L, write_flag = 0L) {
    .Call('_scBIRD_predict', PACKAGE = 'scBIRD', infile0, outfile0, outfile_expr0, locus_model, up_bound, match_mode, write_flag)
}

